DouglasNeuroInformatics/OpenDataCapture

- client/.eslintrc.cjs
- client/src/components/base/Divider/Divider.stories.tsx
- client/src/components/base/Divider/Divider.tsx
- client/src/components/base/Divider/index.ts
- client/src/components/base/index.ts
- client/src/components/form/FieldElement.tsx
- client/src/components/form/FormGroup.tsx
- client/src/components/form/index.ts
- client/src/features/instruments/pages/InstrumentPage.tsx
- client/src/features/subjects/components/SubjectForm.tsx
- client/src/features/subjects/pages/AddSubjectPage.tsx
- common/src/subjects.ts
adds new demographics fields to the add subject form
> add demo fields and divider

- apps/client/package.json
- apps/client/src/Router.tsx
- apps/client/vite.config.js
- yarn.lock
This reverts commit aaa44590f35bfef54ce5cb3550cf59ba86b15c3a.
> Revert "reverse lazy load"

- README.md
> added whitespace to readme

- web/src/features/instruments/components/InstrumentShowcase/InstrumentCard.tsx
> Scale shadow

- web/src/features/instruments/components/InstrumentShowcase/InstrumentCard.tsx
> Update scale to 1.03

- .env.template
- apps/api/src/configuration/configuration.schema.ts
- apps/api/src/prisma/prisma.module.ts
- docker-compose.yaml
Add:
- `MONGO_REPLICA_SET`
- `MONGO_RETRY_WRITES`
- `MONGO_WRITE_CONCERN`
- `MONGO_DIRECT_CONNECTION`
> add additional options for db connection

- apps/playground/package.json
- apps/playground/src/utils/share.ts
- pnpm-lock.yaml
this can drastically reduce the url size for large instruments
> use lz-string to compress source in URL

- apps/web/src/hooks/useInstrumentSummariesQuery.ts
> fix: issue where language on summaries page does not change

- apps/api/src/instruments/instruments.service.ts
- apps/api/src/virtualization/virtualization.service.ts
- apps/web/src/hooks/useInstrument.ts
- apps/web/src/hooks/useInstruments.ts
- packages/instrument-interpreter/src/index.ts
- packages/instrument-library/src/forms/general-consent-form/index.ts
- packages/instrument-library/src/series/happiness-questionnaire-with-consent/index.ts
- packages/instrument-renderer/src/components/InstrumentContent/InstrumentContent.tsx
- packages/instrument-renderer/src/components/InstrumentOverview/InstrumentOverview.tsx
- packages/instrument-renderer/src/components/InstrumentSummary/InstrumentSummary.stories.tsx
- packages/instrument-renderer/src/components/InstrumentSummary/InstrumentSummary.tsx
- packages/instrument-renderer/src/hooks/useInterpretedInstrument.ts
- packages/instrument-stubs/src/series.js
- packages/instrument-utils/src/guards.ts
- packages/instrument-utils/src/measures.ts
- packages/instrument-utils/src/translate.ts
- packages/schemas/src/instrument/__tests__/instrument.base.test.ts
- packages/schemas/src/instrument/__tests__/instrument.core.test.ts
- packages/schemas/src/instrument/instrument.base.ts
- packages/schemas/src/instrument/instrument.core.ts
- packages/schemas/src/instrument/instrument.form.ts
- packages/schemas/src/instrument/instrument.interactive.ts
- packages/schemas/src/instrument/instrument.series.ts
- runtime/v1/src/opendatacapture@1.0.0/core.ts
Also adds `general-consent-form` and `happiness-questionnaire-with-consent` series instrument. Refactors instrument structure to allow for series implementation
> refactor: add `ScalarInstrument` and coherent structure for `SeriesInstrument`

- apps/gateway/package.json
- apps/outreach/package.json
- apps/playground/package.json
- apps/playground/src/components/Header/ActionsDropdown/ActionsDropdown.tsx
- apps/playground/src/components/Header/ActionsDropdown/UploadBundleDialog.tsx
- apps/playground/src/components/Header/ActionsDropdown/UserSettingsDialog.tsx
- apps/playground/src/components/Header/CloneButton/CloneButton.tsx
- apps/playground/src/hooks/useTranspiler.ts
- apps/playground/src/models/settings.model.ts
- apps/playground/src/store/index.ts
- apps/playground/src/store/slices/transpiler.slice.ts
- apps/playground/src/store/types.ts
- apps/web/package.json
- package.json
- packages/i18next/package.json
- packages/instrument-renderer/package.json
- packages/react-core/package.json
- packages/tailwindcss/package.json
- pnpm-lock.yaml
See https://playground.opendatacapture.org/
This currently doesn't work with the demo due to a CORS issue. However, it works with localhost.
> feat: implement upload bundle dialog

- pnpm-lock.yaml
- runtime/v1/package.json
- runtime/v1/src/dompurify@3.1.6/LICENSE
- runtime/v1/src/dompurify@3.1.6/index.d.ts
- runtime/v1/src/dompurify@3.1.6/index.js
- runtime/v1/src/papaparse@5.4.1/LICENSE
- runtime/v1/src/papaparse@5.4.1/index.d.ts
- runtime/v1/src/papaparse@5.4.1/index.js
- runtime/v1/src/pure-rand@6.1.0/LICENSE
- runtime/v1/src/pure-rand@6.1.0/index.d.ts
- runtime/v1/src/pure-rand@6.1.0/index.js
- dompurify@3.1.6
- papaparse@5.4.1
- purerand@6.1.0
> add new libraries to runtime for Cian

- docs/en/2-tutorials/2.1-deployment.md
> docs: add docker version

- apps/playground/src/components/Header/ActionButton/ActionButton.tsx
- apps/playground/src/components/Header/CloneButton/CloneButton.tsx
- apps/playground/src/components/Header/ShareButton/ShareButton.tsx
- docs/en/2-tutorials/2.1-deployment.md
- pnpm-lock.yaml
> changes to playground icons

- apps/web/src/features/admin/pages/CreateUserPage.tsx
- pnpm-lock.yaml
fixes issue where bad request error can happen due to weak password
> update create user form

- apps/api/prisma/schema.prisma
- apps/api/src/demo/demo.service.ts
- apps/api/src/groups/dto/create-group.dto.ts
- apps/api/src/groups/dto/update-group.dto.ts
- apps/api/src/groups/groups.service.ts
- apps/playground/src/vim/adapter.ts
- apps/web/src/features/admin/pages/CreateGroupPage.tsx
- apps/web/src/features/group/components/ManageGroupForm.tsx
- apps/web/src/features/group/pages/ManageGroupPage.tsx
- apps/web/src/features/session/components/StartSessionForm/StartSessionForm.tsx
- apps/web/src/features/setup/pages/SetupPage/SetupPage.tsx
- package.json
- packages/demo/src/index.ts
- packages/schemas/src/core/core.ts
- packages/schemas/src/group/group.ts
- pnpm-lock.yaml
Finalize feature for custom regex to validate subject IDs. Simplifies previous implementation and handles some edge cases. Group managers can define a regex and custom errors messages for feedback (optional in English and French). If no error message is provided in the language, a default message with the regex is provided.
> feat: final subject id regex implementation

- pnpm-lock.yaml
- pnpm-workspace.yaml
> chore: downgrade libnest to v0.1.1

- apps/api/Dockerfile
- apps/gateway/Dockerfile
- apps/web/Dockerfile
> install openssl1.1-compat in docker containers

- apps/api/src/instrument-records/instrument-records.service.ts
- package.json
> provide validation issues when attempting to create an instrument record with invalid data

- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
> feat: update libui package, increment odc version

- apps/api/src/instrument-records/instrument-records.service.ts
- apps/api/src/subjects/subjects.service.ts
- pnpm-lock.yaml
Remove unused code
removed unused p-limit package from lockfile
other fixes from linter
related to #1122
> createMany for upload formating and linting fixes

- apps/api/src/users/users.service.ts
- apps/outreach/astro.config.ts
- apps/outreach/package.json
- apps/outreach/src/styles/main.css
- apps/web/src/features/admin/components/UpdateUserForm.tsx
- package.json
- pnpm-lock.yaml
closes #1131
closes #1128
closes #1127
> fix:  #1131

- apps/api/package.json
- apps/api/src/vendor/configured.auth.module.ts
- apps/web/src/features/admin/components/UpdateUserForm.tsx
- package.json
- packages/schemas/src/core/core.ts
- packages/schemas/src/user/user.ts
- pnpm-lock.yaml
also consolidate duplicated permissions schemas
> fix: issue where additional permissions are not added to the JWT

- apps/web/src/routes/_app/upload/$instrumentId.tsx
- apps/web/src/utils/upload.ts
Works on issue https://github.com/DouglasNeuroInformatics/OpenDataCapture/issues/1163
implements the ability of interpreting zod4 schemas in the upload feature
removes zod4 disabled message
create sample templates for zod4 instruments
interprets csv data of a zod4 instrument
> Zod4 Upload changes
